### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by travisgingrich** [CyberAdvisor/Things-Status-Reporter#1]
error "Things3 got an error: Can’t get area of project id \"A0BAF097-82AA-4115-B507-1025EA2ED7B3\"." number -1728 from area of project id "A0BAF097-82AA-4115-B507-1025EA2ED7B3"

**Comment by CyberAdvisor** [comment]
Are you running this on Things 3 or Things 2? This has only been tested with Things 3

**Comment by travisgingrich** [comment]
Things 3.  Version 3.7.1 (30701502)

**Comment by travisgingrich** [comment]
It happens as I attempt to save the txt file.

**Comment by CyberAdvisor** [comment]
Do you know what Applescript statement you are getting this error on?

**Comment by CyberAdvisor** [comment]
Just found an error when defaultArea is not set. Please download the latest code as I just changed to correct and let me know if that fixed it. v0.1.1

**Comment by CyberAdvisor** [comment]
Found and fixed the error. Download v0.1.2 for fix.
